// ================================================================
// TestCase Studio — Playwright Script
// Name  : Recorded_Test
// Date  : 5/5/2026, 3:14:54 PM
// Steps : 21
// ================================================================
// RUN:
//   npm install && npx playwright install chromium
//   node Recorded_Test.spec.js
// ================================================================
// LOCATOR STRATEGY per element step (tried in order):
//   1. Primary XPath (recorded)
//   2. Primary CSS   (recorded)
//   3. Index-based XPath   e.g. (//button)[4]
//   4. Text-based XPath    e.g. //button[normalize-space()="OK"]
//   5. Partial-ID XPath    e.g. //input[contains(@id,"field-")]
// ================================================================

'use strict';
const { chromium } = require('playwright');

// ─── findElement: tries every locator in order, first match wins ────────────
// Generated by TestCase Studio. Handles dynamic IDs automatically.
async function findElement(locators, stepDesc) {
  const errs = [];
  for (const { label, loc } of locators) {
    try {
      await loc.waitFor({ state: 'attached', timeout: 3000 });
      if (await loc.count() > 0) {
        process.stdout.write('  [✓] ' + stepDesc + ' → ' + label + '\n');
        return loc.first();
      }
      errs.push(label + ': 0 elements matched');
    } catch (e) {
      errs.push(label + ': ' + e.message.split('\n')[0]);
    }
  }
  throw new Error(
    'Element not found for: "' + stepDesc + '"\n' +
    errs.map((e, i) => '  ' + (i + 1) + '. ' + e).join('\n') + '\n' +
    'Tip: Re-record this step if the page structure changed.'
  );
}
// ─────────────────────────────────────────────────────────────────────────────

(async () => {
  const browser = await chromium.launch({ headless: false, slowMo: 80 });
  const context = await browser.newContext();
  const page    = await context.newPage();

  // ── 21 Recorded Steps ─────────────────────────────────────

  // Step 1: Open website
  await page.goto('http://127.0.0.1:8000/');

  // Step 2: Click on "Text"
  // Playwright: page.locator('#text')
  const el_2 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "Text"');
  await el_2.click();

  // Step 3: Enter "Milena" into "Text"
  // Playwright: page.locator('#text')
  const el_3 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Milena" into "Text"');
  await el_3.fill(`Milena`);

  // Step 4: Enter "1234" into "Number"
  // Playwright: page.locator('#number')
  const el_4 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'number\']') },
    { label: 'CSS (primary)', loc: page.locator('#number') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(2)') }
  ], 'Enter "1234" into "Number"');
  await el_4.fill(`1234`);

  // Step 5: Click on "date input"
  // Playwright: page.locator('#date')
  const el_5 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'date\']') },
    { label: 'CSS (primary)', loc: page.locator('#date') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(3)') }
  ], 'Click on "date input"');
  await el_5.click();

  // Step 6: Enter "2026-05-06" into "date input"
  // Playwright: page.locator('#date')
  const el_6 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'date\']') },
    { label: 'CSS (primary)', loc: page.locator('#date') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(3)') }
  ], 'Enter "2026-05-06" into "date input"');
  await el_6.fill(`2026-05-06`);

  // Step 7: Click on "Add"
  // Playwright: page.locator('button[onclick=\'createRecord()\']')
  const el_7 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Add\']') },
    { label: 'CSS (primary)', loc: page.locator('button[onclick=\'createRecord()\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Add"');
  await el_7.click();

  // Step 8: Click on "ID"
  // Playwright: page.locator('#updateId')
  const el_8 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateId\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateId') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "ID"');
  await el_8.click();

  // Step 9: Click on "Text"
  // Playwright: page.locator('#text')
  const el_9 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "Text"');
  await el_9.click();

  // Step 10: Click on "Text"
  // Playwright: page.locator('#text')
  const el_10 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "Text"');
  await el_10.click();

  // Step 11: Double click on "Text"
  // Playwright: page.locator('#text')
  const el_11 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Double click on "Text"');
  await el_11.dblclick();

  // Step 12: Enter "Joseph" into "Text"
  // Playwright: page.locator('#text')
  const el_12 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'text\']') },
    { label: 'CSS (primary)', loc: page.locator('#text') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "Joseph" into "Text"');
  await el_12.fill(`Joseph`);

  // Step 13: Enter "5678" into "Number"
  // Playwright: page.locator('#number')
  const el_13 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'number\']') },
    { label: 'CSS (primary)', loc: page.locator('#number') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[2]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(2)') }
  ], 'Enter "5678" into "Number"');
  await el_13.fill(`5678`);

  // Step 14: Click on "date input"
  // Playwright: page.locator('#date')
  const el_14 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'date\']') },
    { label: 'CSS (primary)', loc: page.locator('#date') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(3)') }
  ], 'Click on "date input"');
  await el_14.click();

  // Step 15: Enter "2026-05-12" into "date input"
  // Playwright: page.locator('#date')
  const el_15 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'date\']') },
    { label: 'CSS (primary)', loc: page.locator('#date') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[3]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(3)') }
  ], 'Enter "2026-05-12" into "date input"');
  await el_15.fill(`2026-05-12`);

  // Step 16: Click on "Add"
  // Playwright: page.locator('button[onclick=\'createRecord()\']')
  const el_16 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//button[normalize-space()=\'Add\']') },
    { label: 'CSS (primary)', loc: page.locator('button[onclick=\'createRecord()\']') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//button)[1]') },
    { label: 'nth-of-type CSS', loc: page.locator('button:nth-of-type(1)') }
  ], 'Click on "Add"');
  await el_16.click();

  // Step 17: Click on "ID"
  // Playwright: page.locator('#updateId')
  const el_17 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateId\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateId') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Click on "ID"');
  await el_17.click();

  // Step 18: Enter "4" into "ID"
  // Playwright: page.locator('#updateId')
  const el_18 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateId\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateId') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[4]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(1)') }
  ], 'Enter "4" into "ID"');
  await el_18.fill(`4`);

  // Step 19: Enter "Joseph" into "Text"
  // Playwright: page.locator('#updateText')
  const el_19 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateText\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateText') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[5]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(2)') }
  ], 'Enter "Joseph" into "Text"');
  await el_19.fill(`Joseph`);

  // Step 20: Enter "5678" into "Number"
  // Playwright: page.locator('#updateNumber')
  const el_20 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateNumber\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateNumber') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[6]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(3)') }
  ], 'Enter "5678" into "Number"');
  await el_20.fill(`5678`);

  // Step 21: Click on "date update"
  // Playwright: page.locator('#updateDate')
  const el_21 = await findElement([
    { label: 'XPath (primary)', loc: page.locator('xpath=//input[@id=\'updateDate\']') },
    { label: 'CSS (primary)', loc: page.locator('#updateDate') },
    { label: 'Index-based XPath', loc: page.locator('xpath=(//input)[7]') },
    { label: 'nth-of-type CSS', loc: page.locator('input:nth-of-type(4)') }
  ], 'Click on "date update"');
  await el_21.click();

  console.log('\n✓ All 21 steps passed.');
  await browser.close();
})().catch(err => {
  console.error('\n✗ Test failed:', err.message);
  process.exit(1);
});